project:
  type: website
  output-dir: docs

website:
  title: "Controle Preditivo" 

  
format:
  html:
    theme: default
    lang: pt-BR
    scss: TemaRTx.scss
    
  revealjs:
    theme: default
    scss: TemaRTx.scss
    transition: slide
    slide-number: true
    footer: ""
    width: 1600      # Largura
    height: 900       # Altura
    code-theme: monokai
    code-font-size: 2.0em
    code-line-numbers: true
    